name: Use Files from Another Repo

on:
  push:
    branches:
      - main

jobs:
  use-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dark.PNG
        uses: actions/checkout@v2
        with:
          #repository: sneha-dhande123/Calculator

          git clone https://github.com/sneha-dhande123/Calculator
          cd Calculator
          git checkout master
          ls

  

